version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    command: python /app/app.py
    working_dir: /app
    volumes:
      - ./backend:/app/backend
      - ./app.py:/app/app.py
      - ./data/cache:/app/data/cache
      - ./data/temp:/app/data/temp
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
